version: '3.7'

services:

    react-ui:
        build:
          context: ./
        ports:
          - "3000:3000"
        container_name: react-ui
        stdin_open: true
        volumes:
           - ./my-app:/usr/src/app/frontend
           - /usr/src/app/frontend/node_modules